### ISSUE TITLE
Update to `dusk-poseidon` 0.23

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/phoenix-core#102]
**Describe what you want implemented** 
Update `dusk-poseidon` dependency to `0.23`.

**Describe "Why" this is needed**
`dusk-plonk` `0.9` was released with major API improvements and general bug fixes. It is desirable to have these improvements available. This is contained in `dusk-poseidon` `0.23`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ureeves** [comment]
This is *definitely* obsolete.
