### ISSUE TITLE
Fee - Generate transparent note

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/phoenix-core#58]
For the transfer contract, we need to generate a remainder note for a given Fee/Crossover pair that will accept as argument the amount of gas consumed by a given transaction.

Currently, we don't have an available API to do that.

#### Proposed solution

Create a function that will take a fee and a consumed gas to generate a transparent note with the remainder value, considering the `gas_limit` attribute of the fee. The value of the note will be `gas_limit - gas_consumed`

**Comment by CPerezz** [comment]
Isn't this closed via #59?
