### ISSUE TITLE
Fee - out of gas exception

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/phoenix-core#65]
The generation of a remainder should fail if it is out of gas, and should return `None` if the gas limit = gas consumed.

Currently, there is an encapsulated workaround to avoid overflows with the assumption that all required checks are executed outside the API.

This assumption is not based on concrete restrictions and could case misuse of the API.

#### Proposed solution

Change the signature of `Fee::gen_remainder(&self, gas_consumed: u64) -> Remainder` to `Fee::gen_remainder(&self, gas_consumed: u64) -> Result<Option<Remainder>, _>`.

Throw `Err(OutOfGas)` if the gas limit is not enough.
Return `None` if `gas limit == gas consumed`

**Comment by ZER0** [comment]
Close as wontfix after a call with @toghrulmaharramov.
